### ISSUE TITLE
Spelling wrong

### ISSUE THREAD

**Issue by mrpkdeveloper** [Pust0/PracticeWebsite#1]
<img width="275" alt="Capture" src="https://user-images.githubusercontent.com/46247882/81506394-9adc1e00-9313-11ea-9ae6-eb71c8905b69.PNG">

Already sold **you** soul (instead of you your has to come)

**Comment by Pust0** [comment]
Dear prateek,

This was a small mistake but thank you for pointing it out. The
registration div was still in progress and possibility of such errors was
near 70%. Although, your contribution has made the progress much faster and
i look forward to such corrections for the common good.
Thank you

**Comment by mrpkdeveloper** [comment]
So I have resolve this issue and now I am closing it. thank you.
